blank_issues_enabled: false

contact_links:
  - name: "ğŸ’¡ Suggestions"
    url: https://github.com/IgorMundstein/WinMemoryCleaner/discussions
    about: "Share your suggestions and ideas in Discussions."

  - name: "ğŸ Report a Bug"
    url: https://github.com/IgorMundstein/WinMemoryCleaner/issues/new?assignees=&labels=bug&template=bug_report.md
    about: "Report bugs using the issue template."

  - name: "ğŸš€ Feature Request"
    url: https://github.com/IgorMundstein/WinMemoryCleaner/issues/new?assignees=&labels=enhancement&template=feature_request.md
    about: "Request new features here."

  - name: "ğŸŒ Translations"
    url: https://github.com/IgorMundstein/WinMemoryCleaner/discussions/14
    about: "Help contribute translations and localization."