blank_issues_enabled: false
issue_templates:
  - name: "âš ï¸ Bug report"
    description: "Report any error or feature that produces an incorrect or unexpected result."
    labels: ["bug"]
    template: "bug_report.yml"
  - name: "ğŸš€ Feature request"
    description: "Suggest an enhancement for this project."
    labels: ["enhancement"]
    template: "feature_request.yml"
  - name: "â“ Question"
    description: "Ask a question about this project."
    labels: ["question"]
    template: "question.yml"
