blank_issues_enabled: false
contact_links:
  - name: â“ Question
    url: https://github.com/IgorMundstein/WinMemoryCleaner/discussions
    about: Please use Discussions.
  - name: ğŸŒ Translation
    url: https://github.com/IgorMundstein/WinMemoryCleaner/discussions/14
    about: If you are a native speaker of any language other than English, you can contribute to this project.
