blank_issues_enabled: false
contact_links:
  - name: "ğŸ’¡ Suggestions"
    url: https://github.com/IgorMundstein/WinMemoryCleaner/discussions/11
    about: "Share your suggestions and ideas in Discussions."

  - name: "ğŸŒ Translations"
    url: https://github.com/IgorMundstein/WinMemoryCleaner/discussions/14
    about: "Help contribute translations and localization."