blank_issues_enabled: false
issue_templates:
  - name: "ğŸ› Bug Report"
    description: "Report an error or feature that produces an incorrect or unexpected result."
    template: "bug_report.yml"
  - name: "ğŸš€ Feature Request"
    description: "Suggest an enhancement for this project."
    template: "feature_request.yml"
  - name: "â“ Question"
    description: "Ask a question about Windows Memory Cleaner."
    template: "question.yml"
  - name: "ğŸŒ Translation Request"
    description: "Contribute a new translation or update an existing one."
    template: "translation_request.yml"
